# Generated by Django 4.2.7 on 2026-01-18 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Timing"),
                            ("exit", "Exit Timing"),
                            ("position", "Position Sizing"),
                            ("risk", "Risk Management"),
                            ("psychology", "Psychology/Emotion"),
                            ("analysis", "Analysis/Research"),
                            ("execution", "Trade Execution"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Trading symbol/ticker (e.g., AAPL, BTC-USD)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the asset (e.g., Apple Inc.)",
                        max_length=100,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("crypto", "Cryptocurrency"),
                            ("forex", "Forex"),
                            ("commodity", "Commodity"),
                            ("option", "Option"),
                            ("future", "Future"),
                            ("other", "Other"),
                        ],
                        default="stock",
                        help_text="Type of financial instrument",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy/Long"), ("sell", "Sell/Short")],
                        help_text="Buy (long) or Sell (short) position",
                        max_length=4,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Number of units/shares/contracts traded",
                        max_digits=20,
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Price at which position was entered",
                        max_digits=20,
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(help_text="When the trade was executed"),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Price at which position was closed (null for open trades)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "exit_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the trade was closed (null for open trades)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about the trade, strategy, emotions, etc.",
                    ),
                ),
                (
                    "mistakes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Mistakes made in this trade (for behavioral learning)",
                        related_name="trades",
                        to="journal.mistake",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        help_text="Trading symbol for this trade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="journal.symbol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made this trade",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-entry_date"],
                        name="journal_tra_user_id_deac48_idx",
                    ),
                    models.Index(
                        fields=["symbol", "-entry_date"],
                        name="journal_tra_symbol__d40096_idx",
                    ),
                ],
            },
        ),
    ]
